import {
  Margherita,
  Paneer,
  GoldenCorn,
  GarlicBread,
} from "../utils/FoodImage";

export const data = [
  {
    RestaurantName: "Domino's Pizza",
    RestaurantImage: "",
    RestaurantTiming: "11am – 12midnight",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Pizza", "French Fries", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Classic Double Cheese Margherita",
        FoodImage: `${Margherita}`,
        FoodRating: 2.5,
        FoodPrice: "229",
        Veg: true,
      },
      {
        FoodName: "Pataka Paneer",
        FoodImage: `${Paneer}`,
        FoodRating: 3,
        FoodPrice: "199",
        Veg: true,
      },
      {
        FoodName: "Golden Corn",
        FoodImage: `${GoldenCorn}`,
        FoodRating: 4.5,
        FoodPrice: "85",
        Veg: true,
      },
      {
        FoodName: "Classic Stuffed Garlic Bread",
        FoodImage: `${GarlicBread}`,
        FoodRating: 3,
        FoodPrice: "149",
        Veg: true,
      },
      {
        FoodName: "Margherita",
        FoodImage: `${Margherita}`,
        FoodRating: 4,
        FoodPrice: "99",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Pizza Hut",
    RestaurantImage: "",
    RestaurantTiming: "1pm – 10pm",
    RestaurantRating: "3.8",
    RestaurantCategory: ["Pizza", "French Fries", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Veggie Feast",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "229",
        Veg: true,
      },
      {
        FoodName: "Margherita",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "149",
        Veg: true,
      },
      {
        FoodName: "Momo Mia Pizza - Veg",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "269",
        Veg: true,
      },
      {
        FoodName: "Tandoori Paneer",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "299",
        Veg: true,
      },
      {
        FoodName: "Garlic Bread Spicy Supreme",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "149",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Ovenstory Pizza",
    RestaurantImage: "",
    RestaurantTiming: "10am – 12midnight",
    RestaurantRating: "4.2",
    RestaurantCategory: ["Pizza", "French Fries", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Corn Veggie Delight Pizza",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "369",
        Veg: true,
      },
      {
        FoodName: "Famous Five Cheese Burst",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "604",
        Veg: true,
      },
      {
        FoodName: "Maharaja Veg Pizza ",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "539",
        Veg: true,
      },
      {
        FoodName: "Spanish Sunshine Pizza",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "459",
        Veg: true,
      },
      {
        FoodName: "Signature Pizzas",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "699",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Burger King",
    RestaurantImage: "",
    RestaurantTiming: "9am – 2am",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Burger", "French Fries", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Crispy Veg Burger",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "55",
        Veg: true,
      },
      {
        FoodName: "Veg Whopper",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "149",
        Veg: true,
      },
      {
        FoodName: "King Fries",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "99",
        Veg: true,
      },
      {
        FoodName: "Tikki Twist Burger",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "60",
        Veg: false,
      },
      {
        FoodName: "King Peri Peri Fries",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "129",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "The Burger Club",
    RestaurantImage: "",
    RestaurantTiming: "9:30am – 4:30am",
    RestaurantRating: "4.3",
    RestaurantCategory: ["Burger", "French Fries", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Veg Club Burger",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "55",
        Veg: true,
      },
      {
        FoodName: "Devil Veg Club Burger",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "179",
        Veg: true,
      },
      {
        FoodName: "Chicken Cheese Club Burger",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "129",
        Veg: false,
      },
      {
        FoodName: "Overloaded Cheesy Fries",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "149",
        Veg: true,
      },
      {
        FoodName: "Devil Chicken Club Burger",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "199",
        Veg: false,
      },
    ],
  },
  {
    RestaurantName: "McDonald's",
    RestaurantImage: "",
    RestaurantTiming: "10am – 10:45pm",
    RestaurantRating: "3.8",
    RestaurantCategory: ["Burger", "French Fries", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "McAloo Tikki™ Burger",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "46",
        Veg: true,
      },
      {
        FoodName: "Fries",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "77",
        Veg: true,
      },
      {
        FoodName: "Pizza McPuff",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "37",
        Veg: true,
      },
      {
        FoodName: "McSpicy™ Chicken Burger",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "169",
        Veg: false,
      },
      {
        FoodName: "Mcspicy™ Paneer Wrap",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "199",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Burger Singh",
    RestaurantImage: "",
    RestaurantTiming: "11am – 1am",
    RestaurantRating: "3.9",
    RestaurantCategory: ["Burger", "French Fries"],
    RestaurantMenu: [
      {
        FoodName: "CHUNKY Paneer Pandey",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "179",
        Veg: true,
      },
      {
        FoodName: "Amritsari Murgh Makhani",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "179",
        Veg: false,
      },
      {
        FoodName: "BIG CRISPY Chicken",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "189",
        Veg: false,
      },
      {
        FoodName: "Udta Punjab 2.0",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "219",
        Veg: false,
      },
      {
        FoodName: "Cheesy Coins",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "69",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "KFC",
    RestaurantImage: "",
    RestaurantTiming: "11am – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Burger", "French Fries", "Biryani", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Big 12 Bucket",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "694",
        Veg: false,
      },
      {
        FoodName: "Classic Zinger",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "170",
        Veg: false,
      },
      {
        FoodName: "Large Popcorn",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "218",
        Veg: false,
      },
      {
        FoodName: "Buddy Meal",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "460",
        Veg: false,
      },
      {
        FoodName: "Tandoori Zinger",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "180",
        Veg: false,
      },
    ],
  },
  {
    RestaurantName: "Taco Bell",
    RestaurantImage: "",
    RestaurantTiming: "11am – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["French Fries", "Wrap"],
    RestaurantMenu: [
      {
        FoodName: "Naked Chicken Taco",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "169",
        Veg: false,
      },
      {
        FoodName: "Crunchy Taco Pinto Bean",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "85",
        Veg: false,
      },
      {
        FoodName: "Mexican Fries",
        FoodImage: "",
        FoodRating: 4.2,
        FoodPrice: "89",
        Veg: true,
      },
      {
        FoodName: "Classic Burrito - Grilled Chicken",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "219",
        Veg: false,
      },
      {
        FoodName: "Vegstar Wrap",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "159",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Chinese Hut",
    RestaurantImage: "",
    RestaurantTiming: "10am – 09pm",
    RestaurantRating: "3.5",
    RestaurantCategory: ["Noodles", "Burger"],
    RestaurantMenu: [
      {
        FoodName: "Veg Hakka Noodles",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "160",
        Veg: true,
      },
      {
        FoodName: "Paneer Burger",
        FoodImage: "",
        FoodRating: 2.5,
        FoodPrice: "65",
        Veg: true,
      },
      {
        FoodName: "Veg Chilli Garlic Noodles",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "80",
        Veg: true,
      },
      {
        FoodName: "Veg Singapuri Noodles",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "95",
        Veg: true,
      },
      {
        FoodName: "Vegstar Burger",
        FoodImage: "",
        FoodRating: 2.5,
        FoodPrice: "40",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Momo's Point",
    RestaurantImage: "",
    RestaurantTiming: "10am – 09pm",
    RestaurantRating: "3.8",
    RestaurantCategory: ["Noodles", "Momo's"],
    RestaurantMenu: [
      {
        FoodName: "Chicken Steamed Momos",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "160",
        Veg: false,
      },
      {
        FoodName: "Chicken Tandoori Momos",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "210",
        Veg: false,
      },
      {
        FoodName: "Veg Hakka Noodles",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "200",
        Veg: true,
      },
      {
        FoodName: "Veg Singapuri Noodles",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "260",
        Veg: true,
      },
      {
        FoodName: "Veg Steamed Momos",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "140",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Haldiram's",
    RestaurantImage: "",
    RestaurantTiming: "9am – 7pm",
    RestaurantRating: "3.0",
    RestaurantCategory: ["Noodles", "Dosa", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Vegetable Noodles",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "209",
        Veg: true,
      },
      {
        FoodName: "Masala Dosa",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "214",
        Veg: true,
      },
      {
        FoodName: "Plain Dosa",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "190",
        Veg: true,
      },
      {
        FoodName: "Badam Heaven Shake",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "99",
        Veg: true,
      },
      {
        FoodName: "Special Desi Ghee Masala Dosa",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "220",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "BTW",
    RestaurantImage: "",
    RestaurantTiming: "10am – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Noodles", "Dosa"],
    RestaurantMenu: [
      {
        FoodName: "Chilly Paneer",
        FoodImage: "",
        FoodRating: 1.5,
        FoodPrice: "190",
        Veg: true,
      },
      {
        FoodName: "Chinese Platter",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "262",
        Veg: true,
      },
      {
        FoodName: "Veg. Noodles",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "152",
        Veg: true,
      },
      {
        FoodName: "Masala Dosa",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "165",
        Veg: true,
      },
      {
        FoodName: "Paneer Dosa",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "210",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "DS Dosa Factory",
    RestaurantImage: "",
    RestaurantTiming: "11am – 11pm ",
    RestaurantRating: "3.9",
    RestaurantCategory: ["Dosa"],
    RestaurantMenu: [
      {
        FoodName: "Ds Chef Special Dosa",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "289",
        Veg: true,
      },
      {
        FoodName: "Flavoured Family Dosa",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "888",
        Veg: true,
      },
      {
        FoodName: "Mushroom Paneer Dosa",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "249",
        Veg: true,
      },
      {
        FoodName: "Butter Paneer Dosa",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "189",
        Veg: true,
      },
      {
        FoodName: "Ghee Roasted Masala Dosa",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "209",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Bikanervala",
    RestaurantImage: "",
    RestaurantTiming: "9am – 10pm",
    RestaurantRating: "3.9",
    RestaurantCategory: ["Noodles", "Dosa", "Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Dosa Butter Masala",
        FoodImage: "",
        FoodRating: 5,
        FoodPrice: "190",
        Veg: true,
      },
      {
        FoodName: "Dosa Paneer",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "220",
        Veg: true,
      },
      {
        FoodName: "Mushroom Paneer Dosa",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "249",
        Veg: true,
      },
      {
        FoodName: "Butter Paneer Dosa",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "189",
        Veg: true,
      },
      {
        FoodName: "Ghee Roasted Masala Dosa",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "209",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Madras Cafe",
    RestaurantImage: "",
    RestaurantTiming: "11am – 11pm ",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Dosa"],
    RestaurantMenu: [
      {
        FoodName: "Masala Dosa",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "80",
        Veg: true,
      },
      {
        FoodName: "Butter Masala Dosa",
        FoodImage: "",
        FoodRating: 3.5,
        FoodPrice: "100",
        Veg: true,
      },
      {
        FoodName: "Special Masala Dosa",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "90",
        Veg: true,
      },
      {
        FoodName: "Mysore Masala Dosa",
        FoodImage: "",
        FoodRating: 2.5,
        FoodPrice: "110",
        Veg: true,
      },
      {
        FoodName: "Butter Special Mix Veg Masala Dosa",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "130",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Biryani Blues",
    RestaurantImage: "",
    RestaurantTiming: "8am – 4am",
    RestaurantRating: "4.2",
    RestaurantCategory: ["Biryani"],
    RestaurantMenu: [
      {
        FoodName: "Hyderabadi Chicken Dum Biryani Boneless",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "299",
        Veg: false,
      },
      {
        FoodName: "Lucknowi Chicken Biryani",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "299",
        Veg: false,
      },
      {
        FoodName: "Hyderabadi Mutton Dum Biryani (Boneless)",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "399",
        Veg: false,
      },
      {
        FoodName: "Paneer Biryani Handi",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "189",
        Veg: false,
      },
      {
        FoodName: "Soya Biryani",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "299",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Biryani By Kilo",
    RestaurantImage: "",
    RestaurantTiming: "10am – 11pm",
    RestaurantRating: "4.4",
    RestaurantCategory: ["Biryani"],
    RestaurantMenu: [
      {
        FoodName: "Chicken Hyderabadi Dum Biryani ",
        FoodImage: "",
        FoodRating: 4.2,
        FoodPrice: "460",
        Veg: false,
      },
      {
        FoodName: "Paneer Dum Biryani",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "325",
        Veg: true,
      },
      {
        FoodName: "Mutton Hyderabadi Dum Biryani",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "645",
        Veg: false,
      },
      {
        FoodName: "Egg Dum Biryani",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "325",
        Veg: false,
      },
      {
        FoodName: "Malamaal Murg Dum Biryani",
        FoodImage: "",
        FoodRating: 3.8,
        FoodPrice: "590",
        Veg: false,
      },
    ],
  },
  {
    RestaurantName: "Khan Chacha",
    RestaurantImage: "",
    RestaurantTiming: "12noon – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Biryani"],
    RestaurantMenu: [
      {
        FoodName: "Veg Biryani",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "260",
        Veg: true,
      },
      {
        FoodName: "Chicken Biryani",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "350",
        Veg: false,
      },
      {
        FoodName: "Mutton Biryani",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "370",
        Veg: false,
      },
    ],
  },
  {
    RestaurantName: "Dunkin' Donuts",
    RestaurantImage: "",
    RestaurantTiming: "7am – 12midnight",
    RestaurantRating: "4.1",
    RestaurantCategory: ["Donuts", "Burger"],
    RestaurantMenu: [
      {
        FoodName: "Gemmy",
        FoodImage: "",
        FoodRating: 4.2,
        FoodPrice: "99",
        Veg: true,
      },
      {
        FoodName: "Crispy Crunch",
        FoodImage: "",
        FoodRating: 4.2,
        FoodPrice: "99",
        Veg: true,
      },
      {
        FoodName: "Rainbow Crunch",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "99",
        Veg: true,
      },
      {
        FoodName: "Big Joy Veg Burger",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "89",
        Veg: true,
      },
      {
        FoodName: "Dark Choco & Strawberry Eclair",
        FoodImage: "",
        FoodRating: 4.5,
        FoodPrice: "99",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Keventers",
    RestaurantImage: "",
    RestaurantTiming: "8am – 2am",
    RestaurantRating: "3.4",
    RestaurantCategory: ["Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Kit-Kat Milkshake",
        FoodImage: "",
        FoodRating: 4.2,
        FoodPrice: "229",
        Veg: true,
      },
      {
        FoodName: "Choco Chip Milkshake",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "219",
        Veg: true,
      },
      {
        FoodName: "Chocolate Oreo Milkshake",
        FoodImage: "",
        FoodRating: 4.1,
        FoodPrice: "209",
        Veg: true,
      },
      {
        FoodName: "Mango Berry Smoothie",
        FoodImage: "",
        FoodRating: 3.8,
        FoodPrice: "229",
        Veg: true,
      },
      {
        FoodName: "Apple Banana Strawberry Smoothie",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "239",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Diggin",
    RestaurantImage: "",
    RestaurantTiming: "11:30am – 11pm",
    RestaurantRating: "3.6",
    RestaurantCategory: ["Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Vanilla Smoothie",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "255",
        Veg: true,
      },
      {
        FoodName: "Peach Smoothie",
        FoodImage: "",
        FoodRating: 3,
        FoodPrice: "255",
        Veg: true,
      },
      {
        FoodName: "Mango and Mint Smoothie",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "255",
        Veg: true,
      },
      {
        FoodName: "Belgium Chocolate Shake",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "255",
        Veg: true,
      },
      {
        FoodName: "Chocolate Mocha Shake",
        FoodImage: "",
        FoodRating: 3.8,
        FoodPrice: "255",
        Veg: true,
      },
    ],
  },
  {
    RestaurantName: "Bistro 57",
    RestaurantImage: "",
    RestaurantTiming: "11am – 10:30pm",
    RestaurantRating: "3.5",
    RestaurantCategory: ["Smoothie"],
    RestaurantMenu: [
      {
        FoodName: "Hazelnut Cold",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "198",
        Veg: true,
      },
      {
        FoodName: "Cold Coffee",
        FoodImage: "",
        FoodRating: 4,
        FoodPrice: "162",
        Veg: true,
      },
    ],
  },
];
