import {
  Domino,
  PizzaHut,
  Ovenstory,
  BurgerKing,
  TheBurgerClub,
  McD,
  BurgerSingh,
  KFC,
  TacoBell,
  ChineseHut,
  MomoPoint,
  Haldiram,
  BTW,
  DsDosa,
  Bikanervala,
  MadrasCafe,
  BiryaniBlues,
  BiryaniByKilo,
  KhanChacha,
  DunkinDonuts,
  Keventers,
  Diggin,
  Bistro57,
} from "../../utils/Images";

export const res = [
  {
    RestaurantName: "Domino's Pizza",
    RestaurantImage: `${Domino}`,
    RestaurantTiming: "11am – 12midnight",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Pizza", "French Fries", "Smoothie"],
  },
  {
    RestaurantName: "Pizza Hut",
    RestaurantImage: `${PizzaHut}`,
    RestaurantTiming: "1pm – 10pm",
    RestaurantRating: "3.8",
    RestaurantCategory: ["Pizza", "French Fries", "Smoothie"],
  },
  {
    RestaurantName: "Ovenstory Pizza",
    RestaurantImage: `${Ovenstory}`,
    RestaurantTiming: "10am – 12midnight",
    RestaurantRating: "4.2",
    RestaurantCategory: ["Pizza", "French Fries", "Smoothie"],
  },
  {
    RestaurantName: "Burger King",
    RestaurantImage: `${BurgerKing}`,
    RestaurantTiming: "9am – 2am",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Burger", "French Fries", "Smoothie"],
  },
  {
    RestaurantName: "The Burger Club",
    RestaurantImage: `${TheBurgerClub}`,
    RestaurantTiming: "9:30am – 4:30am",
    RestaurantRating: "4.3",
    RestaurantCategory: ["Burger", "French Fries", "Smoothie"],
  },
  {
    RestaurantName: "McDonald's",
    RestaurantImage: `${McD}`,
    RestaurantTiming: "10am – 10:45pm",
    RestaurantRating: "3.8",
    RestaurantCategory: ["Burger", "French Fries", "Smoothie"],
  },
  {
    RestaurantName: "Burger Singh",
    RestaurantImage: `${BurgerSingh}`,
    RestaurantTiming: "11am – 1am",
    RestaurantRating: "3.9",
    RestaurantCategory: ["Burger", "French Fries"],
  },
  {
    RestaurantName: "KFC",
    RestaurantImage: `${KFC}`,
    RestaurantTiming: "11am – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Burger", "French Fries", "Biryani", "Smoothie"],
  },
  {
    RestaurantName: "Taco Bell",
    RestaurantImage: `${TacoBell}`,
    RestaurantTiming: "11am – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["French Fries", "Smoothie"],
  },
  {
    RestaurantName: "Chinese Hut",
    RestaurantImage: `${ChineseHut}`,
    RestaurantTiming: "10am – 09pm",
    RestaurantRating: "3.5",
    RestaurantCategory: ["Noodles", "Burger", "French Fries"],
  },
  {
    RestaurantName: "Momo's Point",
    RestaurantImage: `${MomoPoint}`,
    RestaurantTiming: "10am – 09pm",
    RestaurantRating: "3.8",
    RestaurantCategory: ["Noodles", "French Fries"],
  },
  {
    RestaurantName: "Haldiram's",
    RestaurantImage: `${Haldiram}`,
    RestaurantTiming: "9am – 7pm",
    RestaurantRating: "3.0",
    RestaurantCategory: ["Noodles", "Dosa", "Smoothie"],
  },
  {
    RestaurantName: "BTW",
    RestaurantImage: `${BTW}`,
    RestaurantTiming: "10am – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Noodles", "Dosa"],
  },
  {
    RestaurantName: "DS Dosa Factory",
    RestaurantImage: `${DsDosa}`,
    RestaurantTiming: "11am – 11pm ",
    RestaurantRating: "3.9",
    RestaurantCategory: ["Dosa"],
  },
  {
    RestaurantName: "Bikanervala",
    RestaurantImage: `${Bikanervala}`,
    RestaurantTiming: "9am – 10pm",
    RestaurantRating: "3.9",
    RestaurantCategory: ["Noodles", "Dosa", "Smoothie"],
  },
  {
    RestaurantName: "Madras Cafe",
    RestaurantImage: `${MadrasCafe}`,
    RestaurantTiming: "11am – 11pm ",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Dosa"],
  },
  {
    RestaurantName: "Biryani Blues",
    RestaurantImage: `${BiryaniBlues}`,
    RestaurantTiming: "8am – 4am",
    RestaurantRating: "4.2",
    RestaurantCategory: ["Biryani"],
  },
  {
    RestaurantName: "Biryani By Kilo",
    RestaurantImage: `${BiryaniByKilo}`,
    RestaurantTiming: "10am – 11pm",
    RestaurantRating: "4.4",
    RestaurantCategory: ["Biryani"],
  },
  {
    RestaurantName: "Khan Chacha",
    RestaurantImage: `${KhanChacha}`,
    RestaurantTiming: "12noon – 11pm",
    RestaurantRating: "4.0",
    RestaurantCategory: ["Biryani"],
  },
  {
    RestaurantName: "Dunkin' Donuts",
    RestaurantImage: `${DunkinDonuts}`,
    RestaurantTiming: "7am – 12midnight",
    RestaurantRating: "4.1",
    RestaurantCategory: ["Donuts", "Burger"],
  },
  {
    RestaurantName: "Keventers",
    RestaurantImage: `${Keventers}`,
    RestaurantTiming: "8am – 2am",
    RestaurantRating: "3.4",
    RestaurantCategory: ["Smoothie"],
  },
  {
    RestaurantName: "Diggin",
    RestaurantImage: `${Diggin}`,
    RestaurantTiming: "11:30am – 11pm",
    RestaurantRating: "3.6",
    RestaurantCategory: ["Smoothie"],
  },
  {
    RestaurantName: "Bistro 57",
    RestaurantImage: `${Bistro57}`,
    RestaurantTiming: "11am – 10:30pm",
    RestaurantRating: "3.5",
    RestaurantCategory: ["Smoothie"],
  },
];
